CREATE TABLE DIM_DATE (
    DATE_SK INTEGER PRIMARY KEY,
    FULL_DATE DATE,
    DAY_OF_WEEK INTEGER,
    DAY_NAME VARCHAR,
    DAY_OF_MONTH INTEGER,
    WEEK_OF_YEAR INTEGER,
    MONTH_NUMBER INTEGER,
    MONTH_NAME VARCHAR,
    QUARTER INTEGER,
    YEAR INTEGER,
    IS_WEEKEND BOOLEAN,
    IS_EGYPTIAN_HOLIDAY BOOLEAN,
    FISCAL_PERIOD VARCHAR
);
