CREATE TABLE DIM_AGENT (
    AGENT_SK INTEGER PRIMARY KEY,
    AGENT_ID INTEGER,
    HASHED_AGENT_NAME VARCHAR,
    HASHED_AGENT_EMAIL VARCHAR,
    HASHED_AGENT_PHONE VARCHAR,
    SKILL_LEVEL VARCHAR,
    HIRE_DATE DATE,
    AVG_HANDLE_TIME_MIN INTEGER,
    RESOLUTION_RATE DECIMAL(5,2),
    CSAT_SCORE DECIMAL(3,2),
    IS_ACTIVE BOOLEAN,
    TEAM_NAME VARCHAR,
    ROW_EFFECTIVE_TS TIMESTAMP
);
