CREATE TABLE DIM_CUSTOMER (
    CUSTOMER_SK INTEGER PRIMARY KEY,
    CUSTOMER_ID INTEGER,
    HASHED_FULL_NAME VARCHAR,
    HASHED_EMAIL VARCHAR,
    HASHED_PHONE VARCHAR,
    GENDER VARCHAR,
    SIGNUP_DATE DATE,
    SEGMENT_NAME VARCHAR,
    SEGMENT_DISCOUNT_PCT INTEGER,
    SEGMENT_PRIORITY_SUPPORT BOOLEAN,
    CITY_NAME VARCHAR,
    REGION_NAME VARCHAR,
    COUNTRY VARCHAR,
    TIMEZONE VARCHAR,
    DELIVERY_BASE_FEE DECIMAL(18,2),
    IS_ACTIVE BOOLEAN,
    ROW_EFFECTIVE_TS TIMESTAMP
);
