CREATE TABLE DIM_RESTAURANT (
    RESTAURANT_SK INTEGER PRIMARY KEY,
    RESTAURANT_ID INTEGER,
    RESTAURANT_NAME VARCHAR,
    CATEGORY_NAME VARCHAR,
    PRICE_TIER VARCHAR,
    RATING_AVG DECIMAL(3,2),
    PREP_TIME_AVG_MIN INTEGER,
    IS_ACTIVE BOOLEAN,
    CITY_NAME VARCHAR,
    REGION_NAME VARCHAR,
    COUNTRY VARCHAR,
    TIMEZONE VARCHAR,
    DELIVERY_BASE_FEE DECIMAL(18,2),
    ROW_EFFECTIVE_TS TIMESTAMP
);
