CREATE TABLE DIM_REASON (
    REASON_SK INTEGER PRIMARY KEY,
    REASON_ID INTEGER,
    REASON_NAME VARCHAR,
    REASON_CATEGORY_NAME VARCHAR,
    SEVERITY_LEVEL INTEGER,
    TYPICAL_REFUND_PCT DECIMAL(5,2)
)
