CREATE TABLE DIM_PRIORITY (
    PRIORITY_SK INTEGER PRIMARY KEY,
    PRIORITY_ID INTEGER,
    PRIORITY_CODE VARCHAR,
    PRIORITY_NAME VARCHAR,
    SLA_FIRST_RESPONSE_MIN INTEGER,
    SLA_RESOLUTION_MIN INTEGER
);
