CREATE TABLE FACT_TICKET_LIFECYCLE (
    TICKET_SK INTEGER PRIMARY KEY,
    TICKET_ID VARCHAR,
    ORDER_ID VARCHAR,
    
    -- FOREIGN KEYS
    CUSTOMER_SK INTEGER REFERENCES DIM_CUSTOMER(CUSTOMER_SK),
    DRIVER_SK INTEGER REFERENCES DIM_DRIVER(DRIVER_SK),
    RESTAURANT_SK INTEGER REFERENCES DIM_RESTAURANT(RESTAURANT_SK),
    AGENT_SK INTEGER REFERENCES DIM_AGENT(AGENT_SK),
    CHANNEL_SK INTEGER REFERENCES DIM_CHANNEL(CHANNEL_SK),
    PRIORITY_SK INTEGER REFERENCES DIM_PRIORITY(PRIORITY_SK),
    REASON_SK INTEGER REFERENCES DIM_REASON(REASON_SK),
    
    -- DATE/TIME ROLE-PLAYING KEYS
    ORDER_DATE_SK INTEGER REFERENCES DIM_DATE(DATE_SK),
    ORDER_TIME_SK INTEGER REFERENCES DIM_TIME(TIME_SK),
    TICKET_CREATED_DATE_SK INTEGER REFERENCES DIM_DATE(DATE_SK),
    TICKET_CREATED_TIME_SK INTEGER REFERENCES DIM_TIME(TIME_SK),
    FIRST_RESPONSE_DATE_SK INTEGER REFERENCES DIM_DATE(DATE_SK),
    FIRST_RESPONSE_TIME_SK INTEGER REFERENCES DIM_TIME(TIME_SK),
    RESOLVED_DATE_SK INTEGER REFERENCES DIM_DATE(DATE_SK),
    RESOLVED_TIME_SK INTEGER REFERENCES DIM_TIME(TIME_SK),
    REOPENED_DATE_SK INTEGER REFERENCES DIM_DATE(DATE_SK),
    REOPENED_TIME_SK INTEGER REFERENCES DIM_TIME(TIME_SK),
    CLOSED_DATE_SK INTEGER REFERENCES DIM_DATE(DATE_SK),
    CLOSED_TIME_SK INTEGER REFERENCES DIM_TIME(TIME_SK),
    
    -- CATEGORICAL ATTRIBUTES
    TICKET_STATUS VARCHAR,
    ORDER_STATUS VARCHAR,
    
    -- ORDER MEASURES
    ORDER_ITEM_COUNT INTEGER,
    ORDER_SUBTOTAL DECIMAL(18,2),
    ORDER_DISCOUNT_AMOUNT DECIMAL(18,2),
    ORDER_DELIVERY_FEE DECIMAL(18,2),
    ORDER_TOTAL_AMOUNT DECIMAL(18,2),
    
    -- TIMING MEASURES
    ORDER_PREP_TIME_MIN INTEGER,
    ORDER_DELIVERY_TIME_MIN INTEGER,
    ORDER_TOTAL_TIME_MIN INTEGER,
    ORDER_IS_LATE BOOLEAN,
    
    -- SUPPORT PERFORMANCE MEASURES
    FIRST_RESPONSE_TIME_MIN INTEGER,
    RESOLUTION_TIME_MIN INTEGER,
    ORDER_TO_TICKET_TIME_MIN INTEGER,
    SLA_FIRST_RESPONSE_BREACHED BOOLEAN,
    SLA_RESOLUTION_BREACHED BOOLEAN,
    
    -- FINANCIAL IMPACT
    REFUND_AMOUNT DECIMAL(18,2),
    COMPENSATION_AMOUNT DECIMAL(18,2),
    CREDIT_AMOUNT DECIMAL(18,2),
    TOTAL_REVENUE_IMPACT DECIMAL(18,2),
    REFUND_IMPACT_PCT DECIMAL(5,2),
    
    -- AUDIT/META MEASURES
    TOTAL_EVENT_COUNT INTEGER,
    REOPEN_COUNT INTEGER,
    IS_REOPENED BOOLEAN,
    IS_ESCALATED BOOLEAN,
    BATCH_ID VARCHAR
);
