CREATE TABLE IF NOT EXISTS FILE_TRACKING (
    FILE_PATH VARCHAR PRIMARY KEY,
    PROCESSED_AT TIMESTAMP,
    STATUS VARCHAR CHECK (STATUS IN ('PROCESSING', 'SUCCESS', 'FAILED')),
    CURRENT_STAGE VARCHAR DEFAULT 'PENDING',
    RECORD_COUNT INT DEFAULT 0,
    PIPELINE_RUN_ID VARCHAR
);