    CREATE TABLE IF NOT EXISTS FILE_TRACKING (
        FILE_PATH       VARCHAR PRIMARY KEY,
        FILE_HASH       VARCHAR,
        ATTEMPT_COUNT   INTEGER DEFAULT 0,
        STATUS          VARCHAR CHECK (STATUS IN ('PROCESSING', 'SUCCESS', 'FAILED')),
        CURRENT_STAGE   VARCHAR DEFAULT 'PENDING',
        PROCESSED_AT    TIMESTAMP,
        RECORD_COUNT    INTEGER DEFAULT 0,
        PIPELINE_RUN_ID VARCHAR
    )