# -- DROP TABLE IF EXISTS FILE_TRACKING;

# CREATE TABLE IF NOT EXISTS FILE_TRACKING (
#     FILE_PATH VARCHAR,
#     PIPELINE_RUN_ID VARCHAR,
#     PROCESSED_AT TIMESTAMP,
#     STATUS VARCHAR CHECK (STATUS IN ('PROCESSING', 'SUCCESS', 'FAILED')),
#     CURRENT_STAGE VARCHAR DEFAULT 'PENDING',
#     RECORD_COUNT INT DEFAULT 0,
#     LAST_HASH VARCHAR DEFAULT '',
#     PRIMARY KEY (FILE_PATH, PIPELINE_RUN_ID)
#     -- ,LAST_CHECKPOINT TIMESTAMP
# );

import duckdb

def init_db(db_path: str):
    conn = duckdb.connect(db_path)

    conn.execute("""
    CREATE TABLE IF NOT EXISTS FILE_TRACKING (
        FILE_PATH VARCHAR,
        PIPELINE_RUN_ID VARCHAR,
        PROCESSED_AT TIMESTAMP,
        STATUS VARCHAR,
        CURRENT_STAGE VARCHAR,
        RECORD_COUNT INT,
        LAST_HASH VARCHAR,
        PRIMARY KEY (FILE_PATH, PIPELINE_RUN_ID)
    )
    """)

    return conn