database:
  type: duckdb             
  name: fastfeast         
  file: fastfeast.duckdb  
  read_only: false         

paths:
  master_dir: ../data/master
  batch_dir: ../data/input/batch
  stream_dir: ../data/input/stream
  output_dir: ../data/output
  log_file: ../utilities/pipeline.log
  quarantine_file : ../validation
  report_file : ../utilities
  alert_file : ../utilities
  check_point_file : ../utilities/check_point.txt

pipeline:
  batch_size: 1000
  retry_attempts: 3
  #max_threads: 4
  log_level: INFO
  mode : hybrid
# every time we run pipeline for test we may change between batch or stream run,
# change it here

format:
  file_type: parquet

datetime_handling:
  extract_date_key: true
  extract_time_key: true
  date_key_format: "%Y%m%d"
  time_key_format: "%H%M%S"
  keep_original_timestamp: true

logging:
  rotate: daily
  backup_count: 7
  level: INFO

alerts:
  email: supervisor@gmail.com
  on_fail: true

stream:
  poll_interval_sec: 30      # event-based, check every 30 seconds
  file_pattern: "*.parquet"  

batch:
  schedule: daily # time-based
  file_pattern: "*.parquet"  
  max_files_per_run: 10   
# this will be detected through experience with data, or we can calc the time for each batch
# and take the batch with the best time 
  